name: Publish RestQL base Docker image

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+$'

jobs:
  publish:
    name: RestQL tests and build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run unit tests
        shell: bash
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          (cd $(mktemp -d); GO111MODULE=on go get honnef.co/go/tools/cmd/staticcheck@v0.1.3)
          make unit | tee unit-test.log

      - name: Upload unit test logs
        uses: actions/upload-artifact@v2
        with:
          name: tests
          path: unit-test.log
        if: ${{ always() }}

      - name: Run e2e tests
        shell: bash
        run: |
          make e2e-up &
          sleep 10
          make e2e-run | tee e2e-test.log

      - name: Upload e2e test logs
        uses: actions/upload-artifact@v2
        with:
          name: tests
          path: e2e-test.log
        if: ${{ always() }}

      - name: Build restQL
        shell: bash
        run: |
          make build
        env:
          RESTQL_BUILD: ${{ steps.get_version.outputs.version }}

      - name: Upload restQL binary
        uses: actions/upload-artifact@v2
        with:
          name: restQL
          path: ./bin/restQL

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: b2wdigital/restql:${{ steps.get_version.outputs.version }}
