name: Run tests on pull request

on: [pull_request]

jobs:
  publish:
    name: RestQL tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run unit tests
        shell: bash
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          (cd $(mktemp -d); GO111MODULE=on go get honnef.co/go/tools/cmd/staticcheck@v0.1.3)        
          make unit

      - name: Run e2e tests
        shell: bash
        run: |
          make e2e-up &
          sleep 10
          make e2e-run
